#!/bin/bash

FILE=/etc/passwd

read -p "Введите имя пользователя >>> " user_name

file_info=$(grep "^$user_name:" "$FILE")

if [[ -n "$user_name" ]]; then 
	IFS=":" read user pw uid gid name home shell <<< $file_info
	echo "USER  = $user"
	echo "PW    = $pw"
	echo "UID   = $uid"
else
	echo "Имя пользователя не было введено" >&2
	exit 1
fi
exit

blA
